## FacebookAI/roberta-base.yaml

# name
name: roberta-base

# System
seed:  43

# model
architecture: FacebookAI/roberta-base

# Trainer
lr: 0.00001
n_epochs: 3
batch_size: 16
weight_decay: 0.5
scheduler: linear

# data
data_folder:
  train_data: data\down_229744.csv
  test_data: data\test.csv

#save path